---
title: "Примеры"
output: html_document
runtime: shiny
---

```{r, echo=FALSE}
library(shiny)
shinyApp(

  ui = fluidPage(
    selectInput("region", "Region:",
                choices = colnames(WorldPhones)),
    plotOutput("phonePlot")
  ),

  server = function(input, output) {
    output$phonePlot = renderPlot({
      barplot(WorldPhones[,input$region]*1000,
              ylab = "Number of Telephones", xlab = "Year")
    })
  },

  options = list(height = 500)
)
```

```{r, echo=FALSE}
sliderInput("bins", "Number of bins:", 30, min = 1, max = 50)

renderPlot({
  x    = faithful[, 2]  
  bins = seq(min(x), max(x), length.out = input$bins + 1)

  hist(x, breaks = bins, col = 'darkgray', border = 'white')
})
```

```{r eruptions, echo = FALSE}
require(stats) 
plot(cars)
lines(lowess(cars))

plot(sin, -pi, 2*pi) #


plot(table(rpois(100, 5)), type = "h", col = "red", lwd = 10,
     main = "rpois(100, lambda = 5)")


plot(x <- sort(rnorm(47)), type = "s", main = "plot(x, type = \"s\")")
points(x, cex = .5, col = "dark red")

ui <- fluidPage(

  sidebarLayout(
    sidebarPanel(
      fileInput(
        inputId = "file1",
        label = "Загрузите изображение",
        accept = c('image/png', 'image/jpeg','image/jpg')
      ),
      tags$hr()
    ),
    mainPanel(
      textOutput("filename"),
      imageOutput(outputId = "Invoice")
    )
  )
)
server <- function(input, output) {

  re1 <- reactive({
    gsub("\\\\", "/", input$file1$datapath)
  })

  obsB <- observe({
    if(!is.null(input$file1$datapath)) {
      output$Invoice <- renderImage({list(src = re1())}, deleteFile = TRUE)  
      print(input$file1$datapath)
    }
  })
  
}
shinyApp(ui, server)

```

